apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf
resources:
  - ../../base/audiobookshelf
  - audiobookshelf-config.yaml
  - audiobookshelf-metadata.yaml
  - audiobookshelf-audiobooks.yaml
