apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-pv
  namespace: audiobookshelf
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
      #  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k8s-pv/auidobookshelf/"
