apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobook-shelf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: audiobook-shelf
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.17.7
        name: audiobookshelf
        envFrom:
          - configMapRef:
              name: audiobookshelf-configmap
        volumeMounts:
            - mountPath: "/audiobooks"
              name: audiobooks
            - mountPath: "/config"
              name: config
            - mountPath: "/metadata"
              name: metadata
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: audiobookshelf-config
        - name: metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks
