apiVersion: v1
kind: Service
metadata:
  namespace: uptime-kuma
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: uptime-kuma
  name: uptime-kuma
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: uptime-kuma
