apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: uptime-kuma
  labels:
    io.kompose.service: uptime-kuma-claim0
  name: uptime-kuma-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
